<?php

namespace App\Filament\Widgets;

use App\Models\PaymentTransaction;
use App\Models\SubscriptionPlan;
use App\Domain\Billing\Enum\PaymentStatus;
use Filament\Widgets\ChartWidget;
use Illuminate\Support\Facades\DB;

class SubscriptionBreakdownChart extends ChartWidget
{
    protected ?string $heading = 'Monthly Revenue by Plan';
    protected ?string $description = 'Revenue generated by each subscription plan this month';
    protected int|string|array $columnSpan = 1;
    protected ?string $maxHeight = '320px';
    protected ?string $pollingInterval = '2m';
    protected static ?string $slug = 'metrics/subscription-breakdown';

    protected function getData(): array
    {
        // Get all subscription plans
        $plans = SubscriptionPlan::all();
        
        // Get revenue by plan for the current month
        $revenueData = PaymentTransaction::query()
            ->where('status', PaymentStatus::SUCCESSFUL)
            ->whereMonth('paid_at', now()->month)
            ->whereYear('paid_at', now()->year)
            ->whereNotNull('subscription_plan_id')
            ->select(
                'subscription_plan_id',
                DB::raw('SUM(amount) as total_revenue')
            )
            ->groupBy('subscription_plan_id')
            ->get()
            ->keyBy('subscription_plan_id');

        $labels = [];
        $revenues = [];
        $colors = ['#6366F1', '#8B5CF6', '#EC4899', '#F59E0B', '#10B981', '#3B82F6', '#EF4444', '#14B8A6'];

        // Loop through all plans to show even those with $0 revenue
        foreach ($plans as $plan) {
            $revenue = $revenueData[$plan->id] ?? null;
            $amount = $revenue ? round($revenue->total_revenue / 100, 2) : 0;
            
            // Only show plans that have revenue OR are active plans
            // (don't show archived/retired plans with $0)
            if ($amount > 0 || $plan->status === 'active') {
                $labels[] = $plan->name;
                $revenues[] = $amount;
            }
        }

        // If no data, show placeholder
        if (empty($revenues)) {
            return [
                'datasets' => [
                    [
                        'label' => 'Revenue by Plan',
                        'data' => [0],
                        'backgroundColor' => ['#CBD5E1'],
                        'borderRadius' => 6,
                        'borderWidth' => 0,
                    ],
                ],
                'labels' => ['No Revenue This Month'],
            ];
        }

        return [
            'datasets' => [
                [
                    'label' => 'Revenue by Plan',
                    'data' => $revenues,
                    'backgroundColor' => array_slice($colors, 0, count($revenues)),
                    'borderRadius' => 6,
                    'borderWidth' => 0,
                    'maxBarThickness' => 50,
                ],
            ],
            'labels' => $labels,
        ];
    }

    protected function getType(): string
    {
        return 'bar';
    }

    protected function getOptions(): array
    {
        return [
            'plugins' => [
                'legend' => [
                    'display' => false,
                ],
                'tooltip' => [
                    'callbacks' => [
                        'label' => 'function(context) { 
                            return "$" + context.parsed.y.toFixed(2) + " this month";
                        }',
                    ],
                ],
            ],
            'scales' => [
                'y' => [
                    'beginAtZero' => true,
                    'grid' => [
                        'display' => true,
                        'color' => 'rgba(0, 0, 0, 0.05)',
                        'drawBorder' => false,
                    ],
                    'ticks' => [
                        'callback' => 'function(value) { return "$" + value.toFixed(0); }',
                    ],
                ],
                'x' => [
                    'grid' => [
                        'display' => false,
                    ],
                ],
            ],
        ];
    }
}
